version: "3.5"

services:
  server:
    container_name: server
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    command: "npm run startdev"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - linkop
  mongo:
    image: mongo
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - linkop
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    container_name: databaseClient
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - linkop
volumes:
  mongodb_data:
networks:
  linkop:
